version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb_notifications
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
