version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_payments
    ports:
      - "27019:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
