version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_core
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
